DEFAULT_ALLOWED_HOSTS = "localhost,127.0.0.1"

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"
PROJECT_STATUS_MAX_LENGTH = 6

PROJECT_NAME_MAX_LENGTH = 200
SKILL_NAME_MAX_LENGTH = 124

USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

ITEMS_PER_PAGE = 12
SKILLS_SUGGEST_LIMIT = 10

REPOSITORY_HOST = "github.com"
VALID_REPOSITORY_SCHEMES = {"http", "https"}

AVATAR_IMAGE_SIZE = (240, 240)
AVATAR_TEXT_ANCHOR = (0, 0)
AVATAR_TEXT_Y_OFFSET = -8
AVATAR_TEXT_COLOR = (255, 255, 255)

AVATAR_BACKGROUND_COLOR_1 = (60, 78, 97)
AVATAR_BACKGROUND_COLOR_2 = (75, 85, 99)
AVATAR_BACKGROUND_COLOR_3 = (91, 33, 182)
AVATAR_BACKGROUND_COLOR_4 = (29, 78, 216)
AVATAR_BACKGROUND_COLOR_5 = (15, 118, 110)
AVATAR_BACKGROUND_COLORS = [
    AVATAR_BACKGROUND_COLOR_1,
    AVATAR_BACKGROUND_COLOR_2,
    AVATAR_BACKGROUND_COLOR_3,
    AVATAR_BACKGROUND_COLOR_4,
    AVATAR_BACKGROUND_COLOR_5,
]

DEFAULT_AVATAR_LETTER = "U"
